import type { ChatLog } from "@/types/chatbot";

export const MOCK_LOGS: ChatLog[] = [
  {
    id: 1,
    message_sequence: 1,
    question_id: "e323kdse-e32tdjl-3455",
    session_id: "se345-ddk456-fdfin98",
    question_text: "what is the question?",
    chatbot_answer: "Here is my answer. Don't ask again!",
    answer_status: "SUCCESS",
    sources: ["getManualData", "getIndicatorData"],
    feedback_id: 1,
    feedback_type: "LIKE",
    feedback_reason_type: null,
    comment: null,
    latency_ms: 1320,
    user_type: null,
    user_group_id: 26006,
    created_by: 6935,
    created_at: "2026-03-18T06:01:32",
  },
  {
    id: 2,
    message_sequence: 1,
    question_id: "439e7a95-6c4a-426d-8b34-6c573d40a6d3",
    session_id: "561009d9-301a-422d-8efd-dabd4be328b5",
    question_text: "그룹데이터와 개별데이터의 차이점을 알고 싶습니다.",
    chatbot_answer:
      "\n그룹데이터와 개별데이터의 차이점은 다음과 같습니다.\n\n| 구분 | **그룹데이터** | **개별데이터** |\n| :--- | :--- | :--- |\n| **정의** | 지표 + 연도 + 법인 매핑 단위의 데이터입니다. | 실제 데이터가 입력되는 단위입니다. |\n| **특징** | 지표의 관리주기(연간/반기/분기/월간)에 따라 하위에 여러 개의 개별데이터를 가지게 됩니다. | 개별데이터 레벨에서 실제 활동데이터, 첨부파일, 비고 등을 직접 입력하게 됩니다. |\n| **상태 변화** | 소속 개별데이터의 상태에 따라 **미입력 → 산출불가 → 부분산출 → 산출완료**로 구분됩니다. | **미입력 → 입력요청 → 승인대기 → 수정요청 → 승인완료**로 구분됩니다. |",
    answer_status: "SUCCESS",
    sources: ["getManualData"],
    feedback_id: null,
    feedback_type: null,
    feedback_reason_type: null,
    comment: null,
    latency_ms: 31541,
    user_type: null,
    user_group_id: 26006,
    created_by: 6935,
    created_at: "2026-03-18T07:15:35",
  },
  {
    id: 3,
    message_sequence: 2,
    question_id: "4bd8d934-bb68-4f57-96d1-94504662a0ab",
    session_id: "561009d9-301a-422d-8efd-dabd4be328b5",
    question_text: "메롱 지표에 대한 설명해줘",
    chatbot_answer:
      "\n찾으시는 지표를 좀 더 구체적으로 알려주시면 정확한 정보를 안내해 드릴 수 있어요. 😊\n\n아래 중 해당하는 내용을 알려주세요.\n- 지표명 (예: 온실가스 배출량, 에너지 사용량)\n- 지표 코드 (예: ENV_GHG_DIR_EMI_S1_TOT)\n- 관련 카테고리 (예: 환경, 사회, 지배구조)\n- 연관 프레임워크 (예: GRI, SASB, TCFD)\n\n💡 더 자세한 지표 정보는 **[MGT > 지표관리]** 탭에서도 확인하실 수 있습니다.",
    answer_status: "SUCCESS",
    sources: ["getIndicatorData"],
    feedback_id: null,
    feedback_type: null,
    feedback_reason_type: null,
    comment: null,
    latency_ms: 28590,
    user_type: null,
    user_group_id: 26006,
    created_by: 6935,
    created_at: "2026-03-18T07:17:03",
  },
  {
    id: 4,
    message_sequence: 3,
    question_id: "d3402a0a-c1f6-4441-9650-25c29725d953",
    session_id: "561009d9-301a-422d-8efd-dabd4be328b5",
    question_text: "관리기준과 기준연도에 대한 차이점 설명해줘",
    chatbot_answer:
      "\n죄송합니다. 해당 질문에 대한 답변을 찾지 못했습니다.\n더 자세한 내용은 i-ESG(info@i-esg.io)로 문의해 주세요.\n혹시 다른 방식으로 질문해 주시면 다시 찾아볼게요. 😊",
    answer_status: "SUCCESS",
    sources: ["getManualData"],
    feedback_id: null,
    feedback_type: null,
    feedback_reason_type: null,
    comment: null,
    latency_ms: 24548,
    user_type: null,
    user_group_id: 26006,
    created_by: 6935,
    created_at: "2026-03-18T07:17:45",
  },
  {
    id: 5,
    message_sequence: 4,
    question_id: "6aa1579b-6b42-4304-9edc-387a7b8cefaa",
    session_id: "561009d9-301a-422d-8efd-dabd4be328b5",
    question_text: "첨부파일 사용하는 방법 알려주세요",
    chatbot_answer:
      "\n첨부파일을 등록하고 사용하는 방법과 업로드 규격에 대해 안내해 드립니다.\n\n### 1. 첨부파일 등록 방법\n1. [데이터 관리 > 팩트시트] 메뉴로 이동하여 테이블에서 데이터를 클릭해 상세 화면을 엽니다.\n2. 상세 화면의 **데이터 입력** 탭에서 개별데이터의 **첨부파일** 셀을 클릭하여 파일을 업로드할 수 있습니다.\n3. 파일 첨부 후 반드시 **저장** 버튼을 클릭해야 반영됩니다.\n\n### 2. 첨부파일 업로드 규격 및 제한\n- **파일 크기**: 첨부 파일 1개당 **20MB** 사이즈를 초과할 수 없습니다.\n- **업로드 가능한 파일 확장자**:\n  - 문서: docx, pptx, xlsx, pdf\n  - 이미지: jpeg, jpg, png\n  - 데이터: csv\n  - 한글 문서: hwp, hwpx\n- **업로드 불가 확장자**: 위 목록에 포함되지 않은 확장자(예: zip, exe, dmg, mp4, json 등)는 업로드할 수 없습니다.",
    answer_status: "SUCCESS",
    sources: ["getManualData"],
    feedback_id: null,
    feedback_type: null,
    feedback_reason_type: null,
    comment: null,
    latency_ms: 33583,
    user_type: null,
    user_group_id: 26006,
    created_by: 6935,
    created_at: "2026-03-18T07:21:58",
  },
  {
    id: 6,
    message_sequence: 1,
    question_id: "c3024c12-4740-48b7-8eaa-2918d19b4bc6",
    session_id: "6bec23fe-76ce-4273-a6b8-45f21150b3fb",
    question_text: "미산정이 뭐야?",
    chatbot_answer:
      "\n죄송합니다. 해당 질문에 대한 답변을 찾지 못했습니다.\n더 자세한 내용은 i-ESG(info@i-esg.io)로 문의해 주세요.\n혹시 다른 방식으로 질문해 주시면 다시 찾아볼게요. 😊",
    answer_status: "SUCCESS",
    sources: ["getManualData"],
    feedback_id: null,
    feedback_type: null,
    feedback_reason_type: null,
    comment: null,
    latency_ms: 31095,
    user_type: null,
    user_group_id: 26006,
    created_by: 6935,
    created_at: "2026-03-19T00:12:38",
  },
  {
    id: 7,
    message_sequence: 1,
    question_id: "3cf77586-8e72-4227-8d67-8470397c2e02",
    session_id: "4451fffb-85de-4f34-b971-ef433cf9295a",
    question_text: "미산정이 모야",
    chatbot_answer:
      "\n죄송합니다. 해당 질문에 대한 답변을 찾지 못했습니다.\n더 자세한 내용은 i-ESG(info@i-esg.io)로 문의해 주세요.\n혹시 다른 방식으로 질문해 주시면 다시 찾아볼게요. 😊",
    answer_status: "SUCCESS",
    sources: ["getManualData"],
    feedback_id: 6,
    feedback_type: "DISLIKE",
    feedback_reason_type: "INCOMPLETE",
    comment: null,
    latency_ms: 27854,
    user_type: null,
    user_group_id: 26006,
    created_by: 6935,
    created_at: "2026-03-19T01:20:06",
  },
  {
    id: 8,
    message_sequence: 2,
    question_id: "cf62f8e9-98ab-4db1-b75e-38f6c95c0148",
    session_id: "4451fffb-85de-4f34-b971-ef433cf9295a",
    question_text: "미산정이 모야",
    chatbot_answer:
      '\n**미산정(N.C)**과 관련된 내용을 안내해 드립니다.\n\n### 1. 미산정(N.C)의 의미 및 다른 입력값과의 차이\n활동데이터 입력 시 **0**, **N/A**, **미산정(N.C)**은 서로 의미가 다르므로 반드시 구분해서 선택해야 합니다.\n\n| 구분 | 의미 | 계산 및 집계 포함 여부 |\n| --- | --- | --- |\n| **0** | 실제 활동데이터가 존재하며 값이 0인 경우 | 포함 |\n| **N/A** | 해당 법인(조직) 또는 사업/운영에 해당 지표 자체가 애초에 적용되지 않는 경우 | 제외 |\n| **미산정(N.C)** | 해당 지표는 적용 대상이지만 이번 보고기간에 데이터를 산정하지 못한 경우 | 제외 |\n\n### 2. 입력 및 제출 관련 규정\n- **입력 상태 인정**: **미산정(N.C)**은 사용자가 의도적으로 선택한 입력 상태이므로, 데이터 미입력으로 처리되지 않고 **입력 완료 상태**로 간주됩니다.\n- **제출 가능 여부**: 입력 완료 상태로 인정되므로 제출이 가능합니다.\n- **동시 선택 불가**: 값을 입력하면서 N/A 또는 미산정(N.C)을 동시에 선택할 수 없습니다.',
    answer_status: "SUCCESS",
    sources: ["getManualData"],
    feedback_id: 7,
    feedback_type: "LIKE",
    feedback_reason_type: null,
    comment: null,
    latency_ms: 29506,
    user_type: null,
    user_group_id: 26006,
    created_by: 6935,
    created_at: "2026-03-19T01:21:04",
  },
];
